const words3 = {
  офицер: "officer",
  экономист: "economist",
  композитор: "composer",
  певец: "singer",
  музыкант: "musician",
  танцор: "dancer",
  продавец: "shop assistant",
  садовник: "gardener",
  рабочий: "worker",
  парикмахер: "hairdresser",
  официант: "waiter",
  писатель: "writer",
  почтальон: "postman",
  полицейский: "policeman",
  космонавт: ["astronaut", "cosmonaut", "spaceman", "space man"],
  пожарный: "fireman",
  художник: "artist",
  актер: "actor",
  моряк: "sailor",
  водитель: "driver",
  учитель: "teacher",
  летчик: "pilot",
  фермер: "farmer",
  инженер: "engineer",
  врач: "doctor",
};

export { words3 };
