const words4 = {
  гитара: "guitar",
  пианино: "piano",
  скрипка: "violon",
  бег: "running",
  катание_на_лыжах: "skiing",
  хоккей: "hockey",
  футбол: "football",
  плавание: "swimming",
  палатка: "tent",
  велосипед: "bike",
  самокат: "scooter",
  ролики: ["roller skates", "roller-skates"],
  скетборд: "skateboard",
  шахматы: "chess",
  ракетка: "racket",
  фотоаппарат: "camera",
  картина: "picture",
  марка: "stamp",
  конверт: "envelope",
  диск: "disc",
  открытка: "postcard",
  монета: "coin",
  детская_площадка: "playground",
  надувной_шар: "balloon",
  воздушный_змей: "kite",
  скакалка: "jump rope",
  лопата: "shovel",
  ведро: "bucket",
  кукла: "doll",
};

export { words4 };
