const words2 = {
  линейка: "ruler",
  калькулятор: "calculator",
  краски: "paints",
  кисточка: "brush",
  ножницы: "scissors",
  клей: "glue",
  школа: "school",
  доска: ["blackboard", "board"],
  парта: "desk",
  мел: "chalk",
  карта: "map",
  компьютер: "computer",
  ученик: "pupil",
  портфель: "school bag",
  учебник: ["text book", "textbook"],
  тетрадь: "exercise book",
  словарь: ["dictionary", "vocabulary"],
  пенал: "pencil box",
  ручка: "pen",
  карандаш: "pencil",
  точилка: "sharpener",
  ластик: "rubber",
  фломастер: "felt-tip pen",
};

export { words2 };
