const words1 = {
  самолет: "plane",
  корабль: "ship",
  // поезд: "train",
  // мотоцикл: "motor-bike",
  // такси: "taxi",
  // троллейбус: "trolley bus",
  // трамвай: "tram",
  // автобус: "bus",
  // автомобиль: "car",
  // цирк: "circus",
  // почта: "post office",
  // банк: "bank",
  // гостиница: "hotel",
  // галерея: "gallery",
  // кинотеатр: "cinema",
  // музей: "museum",
  // церковь: "church",
  // больница: "hospital",
  // универсам: "supermarket",
  // театр: "theatre",
  // библиотека: "library",
  // кафе: "cafe",
  // фонарь: "lantern",
  // светофор: "traffic lights",
  // мост: "bridge",
  // улица: "street",
};

export { words1 };
